### ISSUE TITLE
Rename Interfaces class as the Base class

### ISSUE THREAD

**Issue by nocotan** [CompML/PRTS#23]
## Summary
To clarify the role of class, we should rename the class as follows:

```
InterfaceTimeSeriesMetrics -> BaseTimeSeriesMetrics
```

This issue will be assigned after all implementations of the interface class are finished.

## Goal

Refactor all corresponding codes. 

## Todo
- [x] rename class name
- [x] rewrite the code which is using the interface class
- [x] check if all unit tests are passed

## Deadline
yyyy / mm / dd  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Other comments.
