### ISSUE TITLE
Implement TimeSeriesPrecisionRecall class

### ISSUE THREAD

**Issue by nocotan** [CompML/PRTS#43]
## Summary
Implement ```TimeSeriesPrecisionRecall``` class.

## Goal
Make it enable us to calculate precision and recall simultaneously.

## Todo
- [ ] ```TimeSeriesPrecisionRecall``` class
- [ ] ```ts_precision_recall``` function
- [ ] unit test of ```TimeSeriesPrecisionRecall``` class
- [ ] unit test of ```ts_precision_recall``` function

## Deadline
yyyy / mm / dd  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Other comments.
