### ISSUE TITLE
Enable to specify "user defined gamma"

### ISSUE THREAD

**Issue by nocotan** [CompML/PRTS#45]
## Summary
Currently, udf_gamma is always 1.
However, it should be specified by users.

Then, I think it is better to modify the argument ```cardinality``` as follows:

```python
assert (cardinality in ["one", "reciprocal", "udf_gamma"]) or isinstance(cardinality, float)
```

## Goal
Modify udf_gamma.

## Todo
- [ ] rewrite init functions of the TimeSeriesPrecision and TimeSeriesRecall.
- [ ] rewrite gamma_function/gamma_select
- [ ] delete udf_gamma() function

## Deadline
yyyy / mm / dd  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Other comments.
