### ISSUE TITLE
Allow argument type: List for F-score

### ISSUE THREAD

**Issue by nocotan** [CompML/PRTS#64]
## Summary
Allow list type as the argument of the f-score function.

## Goal
Allow list type.

## Todo
- [ ] rewrite TimeSeriesFScore class
- [ ] rewrite ts_fscore function
- [ ] add unit tests

## Deadline
yyyy / mm / dd  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Other comments.

**Comment by nocotan** [comment]
Refer [this PR](https://github.com/CompML/PRTS/pull/44)
